title: k-johnston's blog
author: k-johnston
email: kjohnston480@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Information about k-johnston's blog to come.

# social links
github_username:  k-johnston

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
